# -*- coding: utf-8 -*-
"""internship day1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aB1yZVleyFZCTsihUoSfmbpNty5oMbYR

importing libraries
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

df=pd.read_csv("/content/titanic uncleaned.csv")

df

df.head(10)

df.tail(10)

df.info()

df.shape

df.dtypes

df.describe()

df[['Name','Age']]

df.isnull()

"""finding the number of null values

"""

df.isnull().sum()

df['age_mean_inputed']=df['Age'].fillna(df['Age'].mean())
df['age_median_inputed']=df['Age'].fillna(df['Age'].median())

df['age_median_inputed']

df['age_mean_inputed']

df[['Age','age_mean_inputed']]

df['cabin_mode_inputted']=df['Cabin'].fillna(df['Cabin'].mode()[0])

df['cabin_mode_inputted']

"""creating box plot"""

sns.set(style="darkgrid")
plt.figure(figsize=(10,6))
sns.boxplot(data=df,x='Embarked',y='Fare',palette='pastel')

plt.title('Boxplot of Age by Passenger Class',fontsize=12)
plt.xlabel('Passenger Class',fontsize=12)
plt.ylabel('Survived',fontsize=12)
plt.show()

encoded_data=df.copy()
encoded_data

"""label encoding for sex"""

label_encoder=LabelEncoder()
encoded_data['Sex_Label']=label_encoder.fit_transform(encoded_data['Sex'])
encoded_data['Embarked']=label_encoder.fit_transform(encoded_data['Embarked'])
encoded_data['Sex_Label']

"""one hot encoding for embarked"""

one_hot_encoded_data=pd.get_dummies(encoded_data['Embarked'],prefix='Embarked')
encoded_data=pd.concat([encoded_data,one_hot_encoded_data],axis=1)
encoded_data

